In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = sns.load_dataset('iris')

In [3]:

df.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [4]:
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
X= df.drop('species',axis =1)
y = df['species']

In [7]:
X_train, X_test, y_train, y_test = train_test_split(
X, y, test_size=0.33, random_state=42)

In [9]:
from sklearn.neighbors import KNeighborsClassifier

In [14]:
model_knn = KNeighborsClassifier(n_neighbors=13)

In [15]:
model_knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=13)

In [16]:
model_knn.score(X_test, y_test) #if you get 100% accuracy thats means your model is getting in overfit condition

1.0

In [17]:
from sklearn.svm import SVC

In [27]:
model_svm = SVC( gamma = 'auto')

In [28]:
model_svm.fit(X_train, y_train)

SVC(gamma='auto')

In [29]:
model_svm.score(X_test, y_test)

1.0

In [30]:
#now lets use the grid search CV

In [31]:
from sklearn.model_selection import GridSearchCV

In [32]:
classifier = GridSearchCV((model_svm),{
    'C' : [1,10,20,30],
    'kernel' :['rbf','linear'],
},cv = 5,return_train_score = False)

In [33]:

classifier.fit(X,y)

GridSearchCV(cv=5, estimator=SVC(gamma='auto'),
             param_grid={'C': [1, 10, 20, 30], 'kernel': ['rbf', 'linear']})

In [34]:
classifier.cv_results_

{'mean_fit_time': array([0.00718565, 0.00523257, 0.00478692, 0.00642438, 0.00518861,
        0.00391264, 0.00397935, 0.0040484 ]),
 'std_fit_time': array([0.00172352, 0.00061214, 0.00024358, 0.00200933, 0.00031307,
        0.00043366, 0.00038352, 0.00114745]),
 'mean_score_time': array([0.00591531, 0.00386167, 0.00405526, 0.0036294 , 0.00379024,
        0.00294623, 0.00318904, 0.00282021]),
 'std_score_time': array([0.0011818 , 0.00025498, 0.00104542, 0.00034409, 0.00040291,
        0.00040937, 0.00020939, 0.00023379]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20, 30, 30],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear',
                    'rbf', 'linear'],
              mask=[False, False, False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'},
  {'C': 30, 'kernel': 'rbf'},
  {'C': 30, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        , 0.96666667, 1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
        0.9       , 0.9       , 0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333, 0.93333333, 0.9       ]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
        0.96666667, 0.96      , 0.96      ]),
 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
        0.0421637 , 0.03887301, 0.04898979]),
 'rank_test_score': array([1, 1, 1, 4, 5, 6, 7, 7], dtype=int32)}

In [35]:
results = pd.DataFrame(classifier.cv_results_)

In [36]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.007186,0.001724,0.005915,0.001182,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.005233,0.000612,0.003862,0.000255,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.004787,0.000244,0.004055,0.001045,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.006424,0.002009,0.003629,0.000344,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.005189,0.000313,0.003790,0.000403,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,5
5,0.003913,0.000434,0.002946,0.000409,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,6
6,0.003979,0.000384,0.003189,0.000209,30,rbf,"{'C': 30, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.933333,1.0,0.960000,0.038873,7
7,0.004048,0.001147,0.002820,0.000234,30,linear,"{'C': 30, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,7

In [37]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667
6       30          rbf         0.960000
7       30       linear         0.960000

In [38]:
from sklearn.model_selection import RandomizedSearchCV

In [39]:
classifier_r = RandomizedSearchCV((model_svm),{
    'C' : [1,10,20,30],
    'kernel' :['rbf','linear'],
},n_iter = 4,cv = 5,return_train_score = False)

In [40]:
classifier_r.fit(X,y)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=4,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['rbf', 'linear']})

In [41]:
results = pd.DataFrame(classifier_r.cv_results_)

In [42]:
results

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.011661,0.007035,0.005250,0.000904,linear,30,"{'kernel': 'linear', 'C': 30}",1.000000,1.0,0.900000,0.900000,1.0,0.960000,0.048990,4
1,0.005280,0.000347,0.003793,0.000372,rbf,1,"{'kernel': 'rbf', 'C': 1}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.005073,0.001001,0.003598,0.000120,linear,10,"{'kernel': 'linear', 'C': 10}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,3
3,0.006838,0.003595,0.004136,0.000864,rbf,10,"{'kernel': 'rbf', 'C': 10}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1

In [43]:
results[['param_C','param_kernel','mean_test_score']]

   param_C param_kernel  mean_test_score
0       30       linear         0.960000
1        1          rbf         0.980000
2       10       linear         0.973333
3       10          rbf         0.980000